<div class="parent">
  <div class="node">
    <h2 class="title">
        <?php echo $this->node->title; ?> 
        <small>#<?php echo $this->node->id;?></small>
    </h2>
    <div class="dates">
      <div class="dates">
        <em><small>Created at: <span><?php echo date("Y-m-d H:i:s",$this->node->created_at);?></span></small></em>
        <em><small>Updated at: <span><?php echo date("Y-m-d H:i:s",$this->node->updated_at); ?></span></small></em>
      </div>   
    </div>    
    <p class="author"><small><strong>Created by: <span><a href="<?php echo $this->baseUrl()."/user/view/id/".$this->node->user_id; ?>"><?php echo $this->node->username;?></a></span></strong></small></p>   
    <div class="description"><?php echo $this->node->content;  ?></div>
  </div>
</div>
<div class="childs">
<?php foreach ($this->paginator as $child): ?>
  <pre><?php //var_dump($child);?></pre>
  <div class="node" id="child-node-<?php echo $child['id'];?>">
    <h3 class="title">
        <a href="<?php echo $this->baseUrl()."/node/view/id/".$child['id']; ?>"><?php echo $this->escape($child['title']); ?></a>
        <small>#<?php echo $child['id'];?></small>
    </h3>
    <div class="dates">
        <em><small>Created at: <span><?php echo date("Y-m-d H:i:s",$child['created_at']);?></span></small></em>
        <em><small>Updated at: <span><?php echo date("Y-m-d H:i:s",$child['updated_at']); ?></span></small></em>
    </div>    
    <p class="author"><small><strong>Created by: <span><a href="<?php echo $this->baseUrl()."/user/view/id/".$child['user_id']; ?>"><?php echo $child['username'];?></a></span></strong></small></p>   
    <div class="content"><?php echo nl2br( strip_tags( $child['content']) ); ?></div>
    <hr />
  </div>
<?php endforeach; ?>
</div>
<div class="pagination">
    <?php echo $this->paginationControl($this->paginator,'Sliding', 'partials/pagination_control.phtml'); ?>
</div>
<div>
  <a rel="clearboks" href="<?php echo $this->baseUrl()."/node/create/parent_id/".$this->node->id; ?>">Add node</a>
</div>
