<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
<div id="header">
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(
            array('controller'=>'node'),
            'default',
            true) ?>">Homepage</a>
    </div>
</div>
 
<?php echo $this->layout()->content ?>
 
</body>
</html>
