<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>ZForum</title>
  <?php echo $this->headMeta() ?>
  <?php echo $this->headScript() ?> 
  <?php echo $this->headStyle() ?>
  <?php echo $this->headScript()->appendFile('/scripts/jquery-1.4.3.min.js','text/javascript');?>
  <?php echo $this->headScript()->appendFile('/scripts/clearbox.js','text/javascript');?>
  <?php echo $this->headLink()->appendStylesheet('/styles/main.css') ?>
  <script type="text/javascript" src="/scripts/clearbox/config/default/cb_config.js"></script>
  <script type="text/javascript" src="/scripts/clearbox/language/en/cb_language.js"></script>
  <script type="text/javascript" src="/scripts/clearbox/core/cb_core.js"></script>
  <link rel="stylesheet" type="text/css" href="/scripts/clearbox/config/default/cb_style.css">
</head>
<body>
<div id="header">
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(
            array('controller'=>'node'),
            'default',
            true) ?>">Homepage</a>
    </div>
</div>
 
<?php echo $this->layout()->content ?>
 
</body>
</html>
