<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>ZForum</title>
  <?php echo $this->headMeta() ?>
  <?php echo $this->headScript() ?> 
  <?php echo $this->headStyle() ?>
  <?php echo $this->headScript()->appendFile('/scripts/jquery-1.4.3.min.js','text/javascript');?>
  <?php echo $this->headLink()->appendStylesheet('/styles/main.css') ?>
</head>
<body>
<div id="header">
    <h1>Infinity</h1>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(
            array('controller'=>'node'),
            'default',
            true) ?>">Homepage</a>
    </div>
</div>
 
<?php echo $this->layout()->content ?>
<div class="footer">
    <img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" alt="Powered with" />
</div>
</body>
</html>
