<?php echo sprintf($this->translate->_('Welcome to our site. You are now registered with username %s. 
In order to activate your account, please check the email you provided in the registration
process. We have sent you email message with your account information. Please follow the activation link,
which you will find in the email message.'), '<strong>'.$this->escape($this->username).'</strong>') ?>